### ISSUE TITLE
Reset password does not work

### ISSUE THREAD

**Issue by mechanicles** [joemasilotti/railsdevs.io#106]
Reset password does not work.

1. Go to 'https://www.railsdevs.io/users/sign_in'
2. Click on 'Forgot your password?'
3. Enter provided email address
4. Click on `Send reset password instructions`
5. It rails this validation error `Invalid Email or password.`

**Expected behavior**
After clicking `Send reset password instructions` button, it should send a reseting password instruction email I guess.

**Comment by joemasilotti** [comment]
Thanks! Just pushed a fix.
