### ISSUE TITLE
Remove duplicate GitHub Action run on pull requests

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#16]
Every PR seems to be triggering the `test` action twice – one of them should be removed.

**Comment by jacobdaddario** [comment]
What do you mean by this? I looked in the GH interface, and it looks like a test action is only executing once. Additionally, looking through the  file, I don't see any reason that it would have duplicate runs. Could you show an example of how it's not working properly?

**Comment by joemasilotti** [comment]
You're totally right!
