### ISSUE TITLE
Extract common styled elements (form inputs, buttons, error messages, etc.)

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#18]

**Comment by joemasilotti** [comment]
Form inputs/buttons and the Message button are the top two candidates here. @jacobdaddario, this could be a great opportunity to learn about View Components, especially for the Message button.

**Comment by lsparlin** [comment]
Are you open to new contributors?  I like working with view components and have a been hoping to contribute to railsdevs since you announced the idea.

**Comment by joemasilotti** [comment]
Definitely! Please do, all PRs are welcome 😀

**Comment by lsparlin** [comment]
How do you envision component-izing error messages?

**Comment by joemasilotti** [comment]
`app/views/shared/_flash.html.erb` is probably a good candidate, it should DRY up that repeated code for formatting errors vs. messages.

Also, if there's a way to incorporate the `yield` on the last line that would be great. Right now it's being used in `app/views/shared/_error_messages.html.erb`.

**Comment by joemasilotti** [comment]
Diving in a bit more, there are three concepts:

1. Color (blue vs. red) and icon
2. Title (present or not)
3. Content (paragraph vs. list)

A single View Component might be able to handle all of these (with tests!) quite nicely.

**Comment by joemasilotti** [comment]
I would also love to see avatar and cover photos get the same treatment. Currently, there are a lot of `if` statements floating around the views to handle developer's without an attached upload.

**Comment by lsparlin** [comment]
👍 I aim to work on some more `ViewComponent`s for over the next few evenings

**Comment by joemasilotti** [comment]
Closed via #28.
