### ISSUE TITLE
Setup the production environment to take file uploads

### ISSUE THREAD

**Issue by jacobdaddario** [joemasilotti/railsdevs.io#22]
In #20, I setup the app to handle file uploads on the disk for development and test environments. In order to push to a live system, we'll need to configure a remote service to accept uploads. I don't know what you want to do with this @joemasilotti, but I wanted to open this issue to field what you're thinking.

**Comment by joemasilotti** [comment]
Thanks for logging the issue! I can take care of this one once I set up our production environment.

**Comment by joemasilotti** [comment]
Done!
