### ISSUE TITLE
Determine the interaction of direct uploads with ActiveStorage validations

### ISSUE THREAD

**Issue by jacobdaddario** [joemasilotti/railsdevs.io#23]
In #20 I opted to use a direct-upload approach. `active_storage_validations` can handle this, but things get a bit complex. On one hand, it's obvious that if the validations fail, it won't attach the image. For instance, the file doesn't become part of the model.

That said, I was still seeing an upload notification in server logs. This begs the question, what's happening? According to the repo, [the author of the gem isn't sure either](https://github.com/igorkasyanchuk/active_storage_validations#todo). We probably should do some investigation ourselves in order to determine what we have to do to keep the database clean.

**Comment by joemasilotti** [comment]
I'm happy to punt on this until it becomes an issue. S3 storage isn't exactly a huge cost burden at this scale.
