### ISSUE TITLE
Forgot password and resend confirmation pages don’t have styling

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#35]
- [ ] https://www.railsdevs.io/users/password/new
- [ ] https://www.railsdevs.io/users/confirmation/new

![image](https://user-images.githubusercontent.com/2092156/140578336-ff5ac713-4d5e-4f32-9655-d94b7eb596e6.png)

**Comment by davegudge** [comment]
A different issue, but related to password reset. Upon submitting the form, the user is presented with:

![934BC881-A2F5-4B66-B34A-038D5AEF0D06](https://user-images.githubusercontent.com/1736807/140581449-da6d0eff-f819-46aa-9e5f-ccecff99146b.png)

This was using a confirmed user account, that has never signed into the system.

**Comment by davegudge** [comment]
@joemasilotti just an FYI as I can’t edit the title of this issue. The password edit (set a new password) is also suffering from the lack of styling:

https://rails-devs.herokuapp.com/users/password/edit?reset_password_token=XXX

![EDED8DFF-5600-4B52-BF8F-8C470F2E15DD](https://user-images.githubusercontent.com/1736807/140582059-c2e628e9-a918-4a0c-b6f2-e1c69e4db2d7.png)

**Comment by joemasilotti** [comment]
@davegudge, I think the 500 error was because the URL in the email was pointing to the wrong domain. That should be fixed now. Can you try again and if it is still broken open a separate issue?

**Comment by davegudge** [comment]
Hey @joemasilotti,

The domain in the email is now correct, however, the 500 is triggered when submitting the passwords/new form, as opposed to clicking on the reset link in the email.

**Comment by joemasilotti** [comment]
Thanks @davegudge. Please open a new issue so we can track work independently.
