### ISSUE TITLE
Open Graph meta tags

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#37]
* title and `twitter:title`
* description and `twitter:description`
* image and `twitter:image` – hoping to integrate [Mugshot Bot](https://mugshotbot.com) for dynamic images

**Comment by pingortle** [comment]
@joemasilotti I'm on it! Should be able to get to it in the next couple days. Sound good?

**Comment by joemasilotti** [comment]
Awesome! Looking forward to the PR.
