### ISSUE TITLE
Paginate /developers

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#38]
Strong preference for the [pagy gem](https://github.com/ddnexus/pagy) here.

**Comment by A7madXatab** [comment]
I'm on it.

**Comment by A7madXatab** [comment]
Should we be infinite-scrolling or a page links that are clickable?

**Comment by joemasilotti** [comment]
Ideally infinite scroll. But happy to roll with clickable page links and create a new issue for infinite scroll.

**Comment by A7madXatab** [comment]
No worries. Infinite-scroll is easier to implement anyway!.
