### ISSUE TITLE
Developer profiles with name

### ISSUE THREAD

**Issue by thubamamba** [joemasilotti/railsdevs.io#70]
This might be a good one as there's already thought on SEO. Perhaps profile links shouldn't use developers ID but their name. 

I'd be happy to jump on this @joemasilotti.

**Comment by davegudge** [comment]
I've thought about this one too. 

My initial thought was to use the GitHub username, however, it's not mandatory and there is no way to ensure people are 'claiming' their own username. 

Also, the plan is to hide the contact details, so using the GitHub username won't work. I'm sure I read that the developer name was also going to be hidden, so exposing them in the url goes against that? 

An alternative would be to generate a uuid for each developer and use the uuid in the url, but uuid's are long!

Perhaps a randomly generated string, 8 or 10 chars in length, would do the trick for now? This approach does lose the SEO aspect, but would be better than using ids in the url.

**Comment by joemasilotti** [comment]
At this point I'm not planning on exposing a developer's name in the HTML nor the URL string. I agree that it would be better for SEO, but I'm happy to have numbers for now.

Are there any benefits to UUIDs besides hiding how many developers there are? Or the order someone signed up in? What's so bad about using IDs in the URL?

**Comment by davegudge** [comment]
UUIDs are beneficial if you ever need to interface with an external system. 

There's no issue with using the ids in the URL. As you have mentioned, it simply exposes your developer count and the order in which people signed up.

**Comment by joemasilotti** [comment]
Got it. Well, until we interface with an external system I think IDs should be fine. Thanks for the feedback!
