### ISSUE TITLE
Developers are rendered twice on the homepage

### ISSUE THREAD

**Issue by joemasilotti** [joemasilotti/railsdevs.io#78]
@Tonksthebear, I think your PR caused this? Can you please take a look here.

**Comment by Tonksthebear** [comment]
I'm not seeing the issue in Safari. I'll check the others

**Comment by joemasilotti** [comment]
You can see it on `railsdevs.io`. I searched for "experienced web" and the same person showed up twice.

**Comment by Tonksthebear** [comment]
Ah wait I see it. looking now

**Comment by Tonksthebear** [comment]
#80 should fix it. I didn't see anything in my dev environment at least

**Comment by joemasilotti** [comment]
LGTM! Thanks again.
